- name: Playbook - Conmutacion de Etiquetas MPLS
  hosts: mpls_core
  gather_facts: false
  tasks:
    - name: Inicializar Configuracion Global de MPLS y LDP
      cisco.ios.ios_config:
        lines:
          - "mpls label protocol ldp"
      when: mpls_core is defined or mpls_core | default(true)

    - name: MPLS en interfaces
      cisco.ios.ios_config:
        parents:
          - "interface {{ item.name }}"
        lines:
          - "mpls ip"
      loop: "{{ interfaces | default([]) }}" # <--- Corregido: Alineado con cisco.ios.ios_config
      when: interfaces is defined and item.mpls_enabled is defined and item.mpls_enabled == true and item.name != 'Loopback0'
