loopback_ip: 172.16.1.3
interfaces:
  - name: Loopback0
    ip_int: 172.16.1.3
    mask_int: 255.255.255.255
  - name: Ethernet0/1
    ip_int: 10.0.0.10
    mask_int: 255.255.255.252
  - name: Ethernet0/2
    ip_int: 10.0.0.22
    mask_int: 255.255.255.252
  - name: Ethernet0/3
    ip_int: 10.0.0.33
    mask_int: 255.255.255.252
mpls_interfaces:
  - Ethernet0/1
  - Ethernet0/2
  - Ethernet0/3
