# Proveedores:
[pe]
PE1 ansible_host=clab-MPLS-PE1
PE2 ansible_host=clab-MPLS-PE2
[p]
P1 ansible_host=clab-MPLS-P1
P2 ansible_host=clab-MPLS-P2
[rr]
RR1 ansible_host=clab-MPLS-RR1
RR2 ansible_host=clab-MPLS-RR2

# Clientes:
[cpe]
CPE-1 ansible_host=clab-MPLS-CPE-1
CPE-2 ansible_host=clab-MPLS-CPE-2

[mpls_core:children]
pe
p
rr

[switches]
SW-1 ansible_host=clab-MPLS-SW-1
SW-2 ansible_host=clab-MPLS-SW-2

[all:vars]
ansible_network_os=cisco.ios.ios
ansible_connection=network_cli
ansible_user=admin
ansible_password=admin
ansible_ssh_common_args='-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'