COMANDOS = {
    "clab-ISP-TDP-CLARO-IOL-CPE-HQ": [
        "conf terminal",
        "no crypto isakmp key TLN03 address 190.0.0.1",
        "no interface Tunnel1",
        "no crypto ipsec profile PF-TO-BRANCH",
        "no crypto ipsec transform-set TS-TO-BRANCH",
	    "crypto isakmp key TLN03 address 0.0.0.0",
        "crypto ipsec transform-set TS-DMVPN esp-aes esp-sha-hmac",
        "mode transport",
        "exit",

        "crypto ipsec profile PF-DMVPN",
        "set transform-set TS-DMVPN",
        "exit",

        "interface Tunnel1",
        "ip address 172.16.10.1 255.255.255.0",
        "no ip redirects",
        "ip nhrp network-id 100",
        "ip nhrp authentication DMVPNKEY",
        "ip nhrp map multicast dynamic",
        "ip nhrp redirect",
        "tunnel source Loopback0",
        "tunnel mode gre multipoint",
        "tunnel protection ipsec profile PF-DMVPN",
        "tunnel key 100",
        "ip ospf priority 255",
        "ip ospf cost 10",
        "ip ospf hello-interval 5",
        "ip ospf dead-interval 20",
	    "ip ospf network broadcast",
        "exit",
        "router ospf 10",
        "no network 172.16.10.0 0.0.0.3 area 0",
        "network 172.16.10.0 0.0.0.255 area 0",
        "exit",
        "end",
    ],
<<<<<<< HEAD:Topologias/scripts/configs/comandos_modify.py
 
    "clab-ISP-TDP-CLARO-IOL-CPE-HQ-BK": [
=======

    "CPE-HQ-BK": [
>>>>>>> 84a9af3562a43cfd432900bfd7aa943153fa30bb:Topologias/scripts/configs/comandos.py
        "conf terminal",
        "no crypto isakmp key TLN03 address 200.0.1.1",
        "crypto isakmp key TLN03 address 0.0.0.0",
        "no interface Tunnel1",
        "no crypto ipsec profile PF-TO-BRANCH",
        "no crypto ipsec transform-set TS-TO-BRANCH",
        "crypto ipsec transform-set TS-DMVPN esp-aes esp-sha-hmac",
        "mode transport",
        "exit",

        "crypto ipsec profile PF-DMVPN",
        "set transform-set TS-DMVPN",
        "exit",

        "interface Tunnel2",
        "ip address 172.16.20.1 255.255.255.0",
        "no ip redirects",
        "ip nhrp network-id 200",
        "ip nhrp authentication DMVPNKEY",
        "ip nhrp map multicast dynamic",
        "ip nhrp redirect",
        "tunnel source Loopback0",
        "tunnel mode gre multipoint",
        "tunnel protection ipsec profile PF-DMVPN",
	    "tunnel key 200",
        "ip ospf priority 255",
        "ip ospf cost 100",
        "ip ospf hello-interval 5",
        "ip ospf dead-interval 20",
        "exit",
        "router ospf 10",
        "no network 172.16.20.0 0.0.0.3 area 0",
        "network 172.16.20.0 0.0.0.255 area 0",
        "exit",
        "end",
<<<<<<< HEAD:Topologias/scripts/configs/comandos_modify.py
    ],
 
    "clab-ISP-TDP-CLARO-IOL-CPE-BRANCH": [
=======
    ],    

    "CPE-BRANCH": [
>>>>>>> 84a9af3562a43cfd432900bfd7aa943153fa30bb:Topologias/scripts/configs/comandos.py
        "conf terminal",
        "no crypto isakmp key TLN03 address 200.0.0.1",
        "crypto isakmp key TLN03 address 0.0.0.0",
        "no interface Tunnel1",
        "no crypto ipsec profile PF-TO-HQ",
        "no crypto ipsec transform-set TS-TO-HQ",
        "crypto ipsec transform-set TS-DMVPN esp-aes esp-sha-hmac",
        "mode transport",
        "exit",
        "crypto ipsec profile PF-DMVPN",
        "set transform-set TS-DMVPN",
        "exit",
        "interface Tunnel1",
        "ip address 172.16.10.2 255.255.255.0",
        "ip nhrp network-id 100",
        "ip nhrp authentication DMVPNKEY",
        "ip nhrp nhs 172.16.10.1 nbma 200.0.0.1 multicast",
        "ip nhrp shortcut",
        "tunnel source Loopback0",
        "tunnel mode gre multipoint",
        "tunnel protection ipsec profile PF-DMVPN shared",
        "tunnel key 100",
        "ip ospf cost 10",
        "ip ospf hello-interval 5",
        "ip ospf dead-interval 20",
        "ip ospf network broadcast",
        "exit",
        "interface Tunnel2",
        "ip address 172.16.20.2 255.255.255.0",
        "ip nhrp network-id 200",
        "ip nhrp authentication DMVPNKEY",
        "ip nhrp nhs 172.16.20.1 nbma 190.0.1.1 multicast",
        "ip nhrp shortcut",
        "tunnel source Loopback0",
        "tunnel mode gre multipoint",
        "tunnel protection ipsec profile PF-DMVPN shared",
        "tunnel key 200",
        "ip ospf cost 100",
        "ip ospf hello-interval 5",
        "ip ospf dead-interval 20",
        "ip ospf network broadcast",
        "exit",
        "router ospf 10",
        "no network 172.16.10.0 0.0.0.3 area 0",
        "network 172.16.10.0 0.0.0.255 area 0",
        "network 172.16.20.0 0.0.0.255 area 0",
        "exit",
        "end",
    ],
<<<<<<< HEAD:Topologias/scripts/configs/comandos_modify.py
 
    "clab-ISP-TDP-CLARO-IOL-CPE-BRANCH-BK": [
        "conf terminal",
        "no crypto isakmp key TLN03 address 190.0.1.1",
        "crypto isakmp key TLN03 address 0.0.0.0",
        "no interface Tunnel1",
        "no crypto ipsec profile PF-TO-HQ",
        "no crypto ipsec transform-set TS-TO-HQ",
        "crypto ipsec transform-set TS-DMVPN esp-aes esp-sha-hmac",
        "mode transport",
        "exit",
        "crypto ipsec profile PF-DMVPN",
        "set transform-set TS-DMVPN",
        "exit",
        "interface Tunnel1",
        "ip address 172.16.10.3 255.255.255.0",
        "ip nhrp network-id 100",
        "ip nhrp authentication DMVPNKEY",
        "ip nhrp nhs 172.16.10.1 nbma 200.0.0.1 multicast",
        "ip nhrp shortcut",
        "tunnel source Loopback0",
        "tunnel mode gre multipoint",
        "tunnel protection ipsec profile PF-DMVPN shared",
        "ip ospf cost 10",
        "ip ospf hello-interval 5",
        "ip ospf dead-interval 20",
        "exit",
        "interface Tunnel2",
        "ip address 172.16.20.3 255.255.255.0",
        "ip nhrp network-id 200",
        "ip nhrp authentication DMVPNKEY",
        "ip nhrp nhs 172.16.20.1 nbma 190.0.1.1 multicast",
        "ip nhrp shortcut",
        "tunnel source Loopback0",
        "tunnel mode gre multipoint",
        "tunnel protection ipsec profile PF-DMVPN shared",
        "ip ospf cost 100",
        "ip ospf hello-interval 5",
        "ip ospf dead-interval 20",
        "exit",
        "router ospf 10",
        "no network 172.16.20.0 0.0.0.3 area 0",
        "network 172.16.10.0 0.0.0.255 area 0",
        "network 172.16.20.0 0.0.0.255 area 0",
        "exit",
        "end",
    ],
 
    "clab-ISP-TDP-CLARO-IOL-CPE-BRANCH2": [
=======
    "CPE-BRANCH2": [
>>>>>>> 84a9af3562a43cfd432900bfd7aa943153fa30bb:Topologias/scripts/configs/comandos.py
        "conf terminal",
        # Crypto - sin hash md5 ni group 5 que fallan en esta version IOS
        "crypto isakmp policy 10",
        "encr aes",
        "authentication pre-share",
        "group 14",
        "lifetime 1000",
        "exit",
        "crypto isakmp key TLN03 address 0.0.0.0",
        "crypto ipsec transform-set TS-DMVPN esp-aes esp-sha-hmac",
        "mode transport",
        "exit",
        "crypto ipsec profile PF-DMVPN",
        "set transform-set TS-DMVPN",
        "exit",
        # Interfaces
        "interface Loopback0",
        "ip address 180.0.0.1 255.255.255.255",
        "exit",
        "interface Ethernet0/1",
        "ip address 10.0.0.73 255.255.255.252",
        "ip nat outside",
        "no shutdown",
        "exit",
        "interface Ethernet0/2",
        "no ip address",
        "no shutdown",
        "exit",
        "interface Ethernet0/2.25",
        "encapsulation dot1Q 25",
        "ip address 192.168.25.2 255.255.255.0",
        "ip nat inside",
        "vrrp 25 ip 192.168.25.1",
        "vrrp 25 priority 110",
        "vrrp 25 preempt",
        "exit",
        # Tunnels
        "interface Tunnel1",
        "ip address 172.16.10.4 255.255.255.0",
        "ip nhrp network-id 100",
        "ip nhrp authentication DMVPNKEY",
        "ip nhrp nhs 172.16.10.1 nbma 200.0.0.1 multicast",
        "ip nhrp shortcut",
        "tunnel source Loopback0",
        "tunnel mode gre multipoint",
        "tunnel protection ipsec profile PF-DMVPN shared",
        "tunnel key 100",
        "ip ospf cost 10",
        "ip ospf hello-interval 5",
        "ip ospf dead-interval 20",
        "ip ospf network broadcast",
        "exit",
        "interface Tunnel2",
        "ip address 172.16.20.4 255.255.255.0",
        "ip nhrp network-id 200",
        "ip nhrp authentication DMVPNKEY",
        "ip nhrp nhs 172.16.20.1 nbma 190.0.1.1 multicast",
        "ip nhrp shortcut",
        "tunnel source Loopback0",
        "tunnel mode gre multipoint",
        "tunnel protection ipsec profile PF-DMVPN shared",
        "tunnel key 200",
        "ip ospf cost 100",
        "ip ospf hello-interval 5",
        "ip ospf dead-interval 20",
        "ip ospf network broadcast",
        "exit",
        "router ospf 10",
        "router-id 5.5.5.5",
        "network 172.16.10.0 0.0.0.255 area 0",
        "network 172.16.20.0 0.0.0.255 area 0",
        "network 192.168.25.0 0.0.0.255 area 0",
        "passive-interface Ethernet0/2.25",
        "exit",
        # NAT y rutas
        "ip route 0.0.0.0 0.0.0.0 10.0.0.74",
        "ip access-list standard 10",
        "10 permit 192.168.25.0 0.0.0.255",
        "exit",
        "ip nat pool BRANCH2-POOL 180.0.0.2 180.0.0.6 prefix-length 29",
        "ip nat inside source list 10 pool BRANCH2-POOL overload",
        "end",
    ],
<<<<<<< HEAD:Topologias/scripts/configs/comandos_modify.py
 
    "clab-ISP-TDP-CLARO-IOL-CPE-BRANCH2-BK": [
        "conf terminal",
        # Crypto - sin hash md5 ni group 5
        "crypto isakmp policy 10",
        "encr aes",
        "authentication pre-share",
        "lifetime 1000",
        "exit",
        "crypto isakmp key TLN03 address 0.0.0.0",
        "crypto ipsec transform-set TS-DMVPN esp-aes esp-sha-hmac",
        "mode transport",
        "exit",
        "crypto ipsec profile PF-DMVPN",
        "set transform-set TS-DMVPN",
        "exit",
        # Interfaces
        "interface Loopback0",
        "ip address 180.0.1.1 255.255.255.255",
        "exit",
        "interface Ethernet0/1",
        "ip address 10.0.0.77 255.255.255.252",
        "ip nat outside",
        "no shutdown",
        "exit",
        "interface Ethernet0/2",
        "no ip address",
        "no shutdown",
        "exit",
        "interface Ethernet0/2.25",
        "encapsulation dot1Q 25",
        "ip address 192.168.25.3 255.255.255.0",
        "ip nat inside",
        "vrrp 25 ip 192.168.25.1",
        "vrrp 25 priority 100",
        "vrrp 25 preempt",
        "exit",
        # Tunnels
        "interface Tunnel1",
        "ip address 172.16.10.5 255.255.255.0",
        "ip nhrp network-id 100",
        "ip nhrp authentication DMVPNKEY",
        "ip nhrp nhs 172.16.10.1 nbma 200.0.0.1 multicast",
        "ip nhrp shortcut",
        "tunnel source Loopback0",
        "tunnel mode gre multipoint",
        "tunnel protection ipsec profile PF-DMVPN shared",
        "ip ospf cost 10",
        "ip ospf hello-interval 5",
        "ip ospf dead-interval 20",
        "exit",
        "interface Tunnel2",
        "ip address 172.16.20.5 255.255.255.0",
        "ip nhrp network-id 200",
        "ip nhrp authentication DMVPNKEY",
        "ip nhrp nhs 172.16.20.1 nbma 190.0.1.1 multicast",
        "ip nhrp shortcut",
        "tunnel source Loopback0",
        "tunnel mode gre multipoint",
        "tunnel protection ipsec profile PF-DMVPN shared",
        "ip ospf cost 100",
        "ip ospf hello-interval 5",
        "ip ospf dead-interval 20",
        "exit",
        # OSPF
        "router ospf 10",
        "router-id 6.6.6.6",
        "network 172.16.10.0 0.0.0.255 area 0",
        "network 172.16.20.0 0.0.0.255 area 0",
        "network 192.168.25.0 0.0.0.255 area 0",
        "passive-interface Ethernet0/2.25",
        "exit",
        # NAT y rutas
        "ip route 0.0.0.0 0.0.0.0 10.0.0.78",
        "ip access-list standard 10",
        "10 permit 192.168.25.0 0.0.0.255",
        "exit",
        "ip nat pool BRANCH2-BK-POOL 180.0.1.2 180.0.1.6 prefix-length 29",
        "ip nat inside source list 10 pool BRANCH2-BK-POOL overload",
        "end",
    ],
 
    "clab-ISP-TDP-CLARO-IOL-M3": [
=======

    "M3": [
>>>>>>> 84a9af3562a43cfd432900bfd7aa943153fa30bb:Topologias/scripts/configs/comandos.py
        "conf terminal",
        "interface Ethernet1/0",
        "ip address 10.0.0.74 255.255.255.252",
        "ip ospf network point-to-point",
        "no shutdown",
        "exit",
        "router ospf 10",
        "network 10.0.0.72 0.0.0.3 area 0",
        "exit",
        # Ruta estatica - M3 usa redistribute static sin tag
        "ip route 180.0.0.0 255.255.255.248 10.0.0.73",
        "end",
    ],
<<<<<<< HEAD:Topologias/scripts/configs/comandos_modify.py
 
    "clab-ISP-TDP-CLARO-IOL-C5": [
=======

    "SW2-R-PISO1": [
>>>>>>> 84a9af3562a43cfd432900bfd7aa943153fa30bb:Topologias/scripts/configs/comandos.py
        "conf terminal",
        "vlan 25",
        "name VLAN25",
        "exit",
        "interface ethernet0/1",
        "switchport trunk encapsulation dot1q",
        "switchport mode trunk",
        "switchport trunk allowed vlan 25",
        "exit"
        "interface ethernet0/2",
        "switchport trunk encapsulation dot1q",
        "switchport mode trunk",
        "switchport trunk allowed vlan 25",
        "exit",
        "interface ethernet0/3",
        "switchport mode access",
        "switchport access vlan 25",
        "exit",
        "interface ethernet1/0",
        "switchport mode access",
        "switchport access vlan 25",
        "exit"
    ]

}