[MPLS_routers]
clab-MPLS-PE1
clab-MPLS-PE2
clab-MPLS-P1
clab-MPLS-P2
clab-MPLS-RR1
clab-MPLS-RR2

[CPEs]
clab-MPLS-CPE-1
clab-MPLS-CPE-2

[Switches]
clab-MPLS-SW-1
clab-MPLS-SW-2

# Subgrupos utiles para los playbooks
[PE_routers]
clab-MPLS-PE1
clab-MPLS-PE2

[P_routers]
clab-MPLS-P1
clab-MPLS-P2

[RR_routers]
clab-MPLS-RR1
clab-MPLS-RR2

[MPLS_core:children]
PE_routers
P_routers
RR_routers

[all:vars]
ansible_user=admin
ansible_password=admin
ansible_network_os=cisco.ios.ios
ansible_connection=ansible.netcommon.network_cli
ansible_paramiko_look_for_keys=False
