[MPLS_routers]
PE1 ansible_host=clab-MPLS-PE1
PE2 ansible_host=clab-MPLS-PE2
P1  ansible_host=clab-MPLS-P1
P2  ansible_host=clab-MPLS-P2
RR1 ansible_host=clab-MPLS-RR1
RR2 ansible_host=clab-MPLS-RR2

[MPLS_PE]
PE1
PE2

[MPLS_P]
P1
P2

[MPLS_RR]
RR1
RR2

[MPLS_CPE]
CPE1 ansible_host=clab-MPLS-CPE-1
CPE2 ansible_host=clab-MPLS-CPE-2

[MPLS_SW]
SW1 ansible_host=clab-MPLS-SW-1
SW2 ansible_host=clab-MPLS-SW-2

[MPLS_routers:vars]
ansible_network_os=cisco.ios.ios
ansible_connection=ansible.netcommon.network_cli
ansible_user=admin
ansible_password=admin
ansible_become=no

[MPLS_CPE:vars]
ansible_network_os=cisco.ios.ios
ansible_connection=ansible.netcommon.network_cli
ansible_user=admin
ansible_password=admin
ansible_become=no

[MPLS_SW:vars]
ansible_network_os=cisco.ios.ios
ansible_connection=ansible.netcommon.network_cli
ansible_user=admin
ansible_password=admin
ansible_become=no
