---
- name: Configurar Route Reflectors para VPNv4
  hosts: MPLS_RR
  gather_facts: no
  tasks:

    - name: Configurar RR clients en address-family vpnv4
      cisco.ios.ios_config:
        lines:
          - neighbor {{ item }} activate
          - neighbor {{ item }} route-reflector-client
          - neighbor {{ item }} send-community both
        parents:
          - router bgp 100
          - address-family vpnv4
      loop: "{{ vpnv4_clients }}"
      when: vpnv4_clients is defined

- name: Configurar Route Reflectors para VPNv6
  hosts: MPLS_RR
  gather_facts: no
  tasks:

    - name: Configurar RR clients en address-family vpnv6
      cisco.ios.ios_config:
        lines:
          - neighbor {{ item }} activate
          - neighbor {{ item }} route-reflector-client
          - neighbor {{ item }} send-community extended
        parents:
          - router bgp 100
          - address-family vpnv6
      loop: "{{ vpnv4_clients }}"
      when: vpnv4_clients is defined
