---
- name: Configuracion MPLS LDP
  hosts: MPLS_routers
  gather_facts: no
  tasks:

    - name: Habilitar mpls ip global
      cisco.ios.ios_config:
        lines:
          - mpls ip

    - name: Habilitar LDP en interfaces de core
      cisco.ios.ios_config:
        lines:
          - mpls ip
        parents: interface {{ item }}
      loop: "{{ mpls_interfaces }}"
      when: mpls_interfaces is defined
